#pragma once

#define LOG_LEVEL LogLevel::LOG_LEVEL_DEBUG
#define WINDOW_TITLE "Dwarf Hovel"
#define VIRTUAL_WINDOW_WIDTH 256
#define VIRTUAL_WINDOW_HEIGHT 224
#define ACTUAL_WINDOW_WIDTH VIRTUAL_WINDOW_WIDTH*4
#define ACTUAL_WINDOW_HEIGHT VIRTUAL_WINDOW_HEIGHT*4
